---

- name: Install packages
  package:
    name: "{{ packages_to_install[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
    state: present
  tags:
    - package

- name: Create NFS directories
  file:
    path: "{{ item.0.mount }}"
    state: directory
  with_subelements:
    - "{{ nfs }}"
    - clients_groups
  when:
    - groups[item.1] is defined and not none
    - inventory_hostname in groups[item.1]

- name: Start services
  service:
    name: rpcbind
    state: started
    enabled: yes
  when: (ansible_distribution|lower|replace(' ','_')) in ['centos','redhat']
  tags:
    - service

- name: Mount exported NFS into directories
  mount:
    path: "{{ item.0.mount }}"
    src: "{{ item.0.server }}{% if item.0.take_over_network is defined and not none %}-{{item.0.take_over_network}}{% endif %}:{{item.0.export}}"
    fstype: nfs
    opts: "{{ item.0.mount_arguments }}"
    state: mounted
  with_subelements:
    - "{{ nfs }}"
    - clients_groups
  when:
    - groups[item.1] is defined and not none
    - inventory_hostname in groups[item.1]
