---
- name: Install packages
  package:
    name: "{{packages_to_install[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version]}}"
    state: present
  tags:
    - package

- name: Create needed directory >> /var/named
  file:
   path: /var/named
   state: directory
   mode: 0755

- name: Template >> /etc/named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dns services
  tags:
    - template

- name: Template >> /var/named/forward
  template:
    src: forward.j2
    dest: /var/named/forward
    owner: root
    group: root
    mode: 0644
  notify: Restart dns services
  tags:
    - template

- name: Template >> /var/named/reverse
  template:
    src: reverse.j2
    dest: /var/named/reverse
    owner: root
    group: root
    mode: 0644
  notify: Restart dns services
  tags:
    - template

- meta: flush_handlers

- name: Enable/disable services
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  tags:
    - service

- name: Start services
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  when: (start_services | bool)
  tags:
    - service
